version: '3'
services:
  golang:
    build: .
    container_name: golang
    tty: true 
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src:rw
    networks:
      - lnmp
    environment:
      GOPROXY: "https://goproxy.cn"

networks:
  lnmp:
    external:
      name: docker